name: Adding Algorithm/Code
description: Adding any Algorithm/Code in Python
title: "add: <title>"
labels: ["good-first-issue"]
body:
  - type: textarea
    attributes:
      label: Describe the algorithm/code
      description: Provide a clear and concise description of what you are going to implement.
    validations:
      required: true
  - type: checkboxes
    id: want_to_work
    attributes:
      label: Do you want to work on this feature?
      description: You can also contribute a viable solution to the proposed feature, via discussion and code.
      options:
        - label: I am willing to implement this feature.
          required: false
          
