name: Adding Documentation
description: Request a new addition to documentation (CONTRIBUTING.md, README.md, etc.)
title: "add: <title>"
labels: ["documentation", "good-first-issue"]
body:
  - type: textarea
    attributes:
      label: Describe the addition
      description: Provide a clear and concise description of what you are trying to add.
    validations:
      required: true
  - type: checkboxes
    id: want_to_work
    attributes:
      label: Do you want to work on this feature?
      description: You can also contribute a viable solution to the proposed documentation, via discussion and code.
      options:
        - label: I am willing to implement this feature.
          required: false
