name: Modifying Existing Documentation
description: Request a modification to current documentation (CONTRIBUTING.md, README.md, etc.)
title: "update: <title>"
labels: ["enhancement", "good-first-issue"]
body:
  - type: textarea
    attributes:
      label: Describe the improvement
      description: Provide a clear and concise description of what the problem is and how you will be solving that.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Do you have a proposed solution?
      description: Provide a clear and concise description of suggestions on how this modifications can be implemented. 
    validations:
      required: true
  - type: checkboxes
    id: want_to_work
    attributes:
      label: Do you want to work on this feature?
      description: You can also contribute a viable solution to the proposed feature, via discussion and code.
      options:
        - label: I am willing to implement this feature.
          required: false
